In [1]:
import pandas as pd

loyalty = pd.read_csv("Customer Loyalty History.csv")

In [2]:
loyalty.head()

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [3]:
loyalty.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Salary', 'Marital Status', 'Loyalty Card',
       'CLV', 'Enrollment Type', 'Enrollment Year', 'Enrollment Month',
       'Cancellation Year', 'Cancellation Month'],
      dtype='object')

In [4]:
loyalty.shape

(16737, 16)

In [5]:
loyalty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB

In [6]:
import pandas as pd

In [7]:
loyalty = pd.read_csv("Customer Loyalty History.csv")

In [8]:
loyalty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB

In [9]:
loyalty.describe()

,Loyalty Number,Salary,CLV,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
count,16737.000000,12499.000000,16737.000000,16737.000000,16737.000000,2067.000000,2067.000000
mean,549735.880445,79245.609409,7988.896536,2015.253211,6.669116,2016.503145,6.962748
std,258912.132453,35008.297285,6860.982280,1.979111,3.398958,1.380743,3.455297
min,100018.000000,-58486.000000,1898.010000,2012.000000,1.000000,2013.000000,1.000000
25%,326603.000000,59246.500000,3980.840000,2014.000000,4.000000,2016.000000,4.000000
50%,550434.000000,73455.000000,5780.180000,2015.000000,7.000000,2017.000000,7.000000
75%,772019.000000,88517.500000,8940.580000,2017.000000,10.000000,2018.000000,10.000000
max,999986.000000,407228.000000,83325.380000,2018.000000,12.000000,2018.000000,12.000000

In [10]:
loyalty.isnull().sum()

Loyalty Number            0
Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                 4238
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64

In [11]:
loyalty["loyalty card"].value_counts()

KeyError: 'loyalty card'

In [ ]:
loyalty["Loyalty Card"].value_counts()

In [ ]:
loyalty["Salary"].mean()

In [ ]:
loyalty["CLV"].mean()

In [ ]:
loyalty.sort_values(by="CLV",ascending=False).head()

In [ ]:
loyalty["Cancellation Year"].isnull().sum()

In [ ]:
loyalty["Churn"]=loyalty["Cancellation Year"].notnull()

In [ ]:
loyalty.head()

In [ ]:
loyalty["Churn"].value_counts()

In [ ]:
loyalty["Churn"].mean()

In [ ]:
loyalty.groupby("Loyalty Card")["Churn"].mean()*100

In [ ]:
loyalty.groupby("Gender")["Churn"].mean() * 100

In [ ]:
loyalty.groupby("Marital Status")["Churn"].mean() * 100

In [ ]:
loyalty.groupby("Loyalty Card")["CLV"].mean()

In [ ]:
loyalty.groupby("Education")["Salary"].mean()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd

In [ ]:
loyalty["Churn"].value_counts().plot(kind="bar")

In [ ]:
plt.title("customer churn distribution")

In [ ]:
loyalty["Churn"].value_counts().plot(kind="bar")

plt.title("Customer Churn Distribution")

plt.xlabel("Churn Status")
plt.ylabel("Number of Customers")

In [ ]:
loyalty["Loyalty Card"].value_counts().plot(kind="bar")
plt.title("loyalty card distribution")
plt.xlabel("loyalty card type")
plt.ylabel("number of customers")

In [ ]:
loyalty["Gender"].value_counts().plot(kind="bar")

plt.title("Gender Distribution")

plt.xlabel("Gender")
plt.ylabel("Number of Customers")

In [ ]:
loyalty["Salary"].plot(kind="hist")
plt.title("Salary distribution")
plt.xlabel("Salary")
plt.ylabel("frequency")

In [ ]:
loyalty["CLV"].plot(kind="hist")

plt.title("Customer Lifetime Value Distribution")

plt.xlabel("CLV")
plt.ylabel("Frequency")

In [ ]:
import pandas as pd
loyalty = pd.read_csv("Customer Loyalty History.csv")
loyalty.head()

In [ ]:
loyalty.columns

In [ ]:
loyalty["Churn"] = loyalty["Cancellation Year"].notnull()

In [ ]:
loyalty.columns

In [ ]:
activity = pd.read_csv("Customer Flight Activity.csv")

In [ ]:
activity.head()

In [ ]:
activity.info()

In [ ]:
 activity.head()

In [ ]:
activity["Loyalty Number"].nunique()

In [ ]:
activity.groupby("Loyalty Number")[["Total Flights",
                                    "Distance",
                                    "Points Accumulated",
                                    "Points Redeemed"]].sum().head()

In [ ]:
activity.groupby("Loyalty Number")[["Total Flights",
                                    "Distance",
                                    "Points Accumulated",
                                    "Points Redeemed"]].sum().head()

In [ ]:
activity_summary = activity.groupby("Loyalty Number")[[
    "Total Flights",
    "Distance",
    "Points Accumulated",
    "Points Redeemed"
]].sum()

In [ ]:
activity_summary.head()

In [ ]:
final_data = loyalty.merge(
    activity_summary,
    on="Loyalty Number"
)

In [ ]:
final_data.head()

In [ ]:
final_data.shape

In [ ]:
"Churn" in final_data.columns

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

final_data["Gender"] = le.fit_transform(final_data["Gender"])

final_data[["Gender"]].head()

In [ ]:
categorical_cols = [
    "Country",
    "Province",
    "City",
    "Education",
    "Marital Status",
    "Loyalty Card",
    "Enrollment Type"
]

for col in categorical_cols:
    final_data[col] = le.fit_transform(final_data[col])

In [ ]:
final_data.head()

In [ ]:
final_data.isnull().sum()

In [ ]:
final_data["Salary"] = final_data["Salary"].fillna(
    final_data["Salary"].median()
)

In [ ]:
final_data.isnull().sum()

In [ ]:
features = [
    "Gender",
    "Education",
    "Salary",
    "Loyalty Card",
    "CLV",
    "Total Flights",
    "Distance",
    "Points Accumulated",
    "Points Redeemed"
]

In [ ]:
X = final_data[features]

y = final_data["Churn"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
model = LogisticRegression(max_iter=5000)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, predictions)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, predictions)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, predictions))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_predictions = rf.predict(X_test)

accuracy_score(y_test, rf_predictions)

In [ ]:
X = final_data[features]

y = final_data["Churn"]

In [ ]:
loyalty.head()

In [ ]:
final_data.shape

In [ ]:
loyalty["Loyalty Card"].value_counts()

In [ ]:
final_data.shape

In [ ]:
loyalty.shape

In [ ]:
activity.shape

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
final_data.shape

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [ ]:
rf.fit(X_train, y_train)

In [ ]:
X = final_data.drop("Churn", axis=1)
y = final_data["Churn"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

In [ ]:
X_train.dtypes

In [ ]:
X = final_data.drop(["Churn", "Postal Code"], axis=1)

y = final_data["Churn"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

In [ ]:
rf_predictions = rf.predict(X_test)

In [ ]:
accuracy_score(y_test, rf_predictions)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, rf_predictions)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, rf_predictions))

In [ ]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

feature_importance.sort_values(
    by="Importance",
    ascending=False
).head(10)

In [ ]:
X = final_data.drop(
    ["Churn", "Postal Code", "Cancellation Year", "Cancellation Month"],
    axis=1
)

y = final_data["Churn"]

In [ ]:
X = final_data.drop(
    ["Churn", "Postal Code", "Cancellation Year", "Cancellation Month"],
    axis=1
)

y = final_data["Churn"]

In [ ]:
loyalty.shape

In [ ]:
rf

In [ ]:
rf.feature_importances_

In [ ]:
rf.fit(X_train, y_train)

In [ ]:
X.columns

In [ ]:
X = final_data.drop(
    ["Churn",
     "Postal Code",
     "Cancellation Year",
     "Cancellation Month"],
    axis=1
)

y = final_data["Churn"]

In [ ]:
X.columns

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

In [ ]:
rf.feature_importances_

In [ ]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

feature_importance.sort_values(
    by="Importance",
    ascending=False
).head(10)

# Business Insights

### Insight 1
Customers' enrollment year is the strongest predictor of churn.

### Insight 2
Customers with fewer flights are more likely to churn.

### Insight 3
Travel distance significantly influences customer loyalty behaviour.

### Insight 4
Customers who accumulate more loyalty points show lower churn tendency.

### Insight 5
Point redemption activity contributes to churn prediction.

In [ ]:
accuracy_score(y_test, rf_predictions)

# Model Comparison

In [ ]:
| Model | Accuracy |
|---------|---------|
| Logistic Regression | 89.39% |
| Random Forest | 88.56% |

Conclusion:

Logistic Regression achieved slightly higher accuracy than Random Forest on this dataset and was selected as the final model.

# Model Comparison

| Model | Accuracy |
|---------|---------|
| Logistic Regression | 89.39% |
| Random Forest | 88.56% |

Conclusion:

Logistic Regression achieved slightly higher accuracy than Random Forest on this dataset and was selected as the final model.

# Recommendations

1. Target low-flight customers with retention campaigns.

2. Encourage customers to earn and redeem loyalty points.

3. Identify at-risk customers early using churn prediction models.

4. Increase customer engagement through loyalty program benefits.

5. Provide personalized offers to improve customer retention.

# Conclusion

This project analyzed airline customer loyalty and flight activity data to predict customer churn. Logistic Regression and Random Forest models were used for prediction. Logistic Regression achieved the highest accuracy of approximately 89.4%. The analysis identified enrollment year, flight activity, travel distance, and loyalty point activity as key factors influencing churn. These insights can help airlines improve customer retention strategies.

In [12]:
import os
print(os.getcwd())

C:\Users\Lenovo

In [13]:
dir *.ipynb

SyntaxError: invalid syntax (575117901.py, line 1)

In [14]:
import os
from pathlib import Path

print(Path().resolve())
print(os.listdir())

C:\Users\Lenovo
['.anaconda', '.antigravity', '.bash_history', '.cache', '.codetogether', '.conda', '.continuum', '.copilot', '.ctsystem', '.gemini', '.git', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.keras', '.lesshst', '.matplotlib', '.ms-ad', '.python_history', '.viminfo', '.virtual_documents', '.vscode', '.vscode-shared', 'Airline Loyalty Data Dictionary (1).csv', 'airline_project', 'airline_project.ipynb', 'anaconda3', 'AppData', 'Application Data', 'c course', 'Calendar.csv', 'Contacts', 'Cookies', 'Customer Flight Activity.csv', 'Customer Loyalty History.csv', 'data', 'data - Copy', 'Desktop', 'Documents', 'Favorites', 'github-classroom', 'html tutorial', 'images', 'Links', 'Local Settings', 'MatSci_Project_Phase1 (1).ipynb', 'MatSci_Project_Phase1.ipynb', 'metadata.csv', 'Microsoft', 'ML materials science project', 'ML materials science project.ipynb', 'ML_Project', 'Music', 'My Documents', 'NetHood', 'nitk-assist-project-ishitastudent-lab', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{363674d1-ec21-11f0-af59-c6445284815b}.TM.blf', 'NTUSER.DAT{363674d1-ec21-11f0-af59-c6445284815b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{363674d1-ec21-11f0-af59-c6445284815b}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'Postman', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'tut1.cpp', 'tut2.cpp', 'Untitled Folder', 'Untitled.ipynb', 'untitled.txt', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Videos']